/* AUTOGENERATED FILE - DO NOT EDIT CONTENTS */

// 環境変数の安全な取得
const getEnvVar = (key: string): string | undefined => {
  try {
    return typeof import.meta !== 'undefined' && import.meta.env ? import.meta.env[key] : undefined;
  } catch {
    return undefined;
  }
};

// Supabase URL からプロジェクトIDを取得
const getProjectIdFromUrl = (url?: string): string => {
  if (!url) return "hyqefzhiugwacdrilhwr";
  try {
    return new URL(url).hostname.split('.')[0];
  } catch {
    return "hyqefzhiugwacdrilhwr";
  }
};

// 本番環境では環境変数を使用、開発環境ではデフォルト値を使用
export const projectId = getProjectIdFromUrl(
  getEnvVar('VITE_SUPABASE_URL') || "https://hyqefzhiugwacdrilhwr.supabase.co"
);

export const publicAnonKey = getEnvVar('VITE_SUPABASE_ANON_KEY') 
  || "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imh5cWVmemhpdWd3YWNkcmlsaHdyIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTM5NDY0MTYsImV4cCI6MjA2OTUyMjQxNn0.KH1fesa5dCmshgaOLm7TXq0YvBPwoK6C8vRuBQOQ95w";